print("이름을 입력하세요 : ", end="")
name = input()
print("학번을 입력하세요 : ", end="")
number = input()
print("학과를 입력하세요 : ", end="")
study = input()

print("이름 : ", name)
print("학번 : ", number)
print("학과 : ", study)
